spring:
  application:
    name: br.com.api-pessoal

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/db_test
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

server:
  port: ${PORT:8080}
  error:
    include-stacktrace: never

app:
  token:
    secret-key: ${JWT_SECRET_KEY:Y3Vyc28tYXV0ZW50aWNhY2FvLXN0YXRlZnVsLXN0YXRlbGVzcy1taWNyb3NzZXJ2aWNvcw==}

security:
  config:
    prefix: Bearer
    key: SECRET_KEY
    expiration: 3600000


